# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2027dc7f02eb4932120f2b3c435079b846cac9d7de0ce79024e926fe4a2c43ec63f289c4a1aa3b200d097f86bcfa9f49688375e1ace986066aacff7c32e11879

test:
  secret_key_base: 490890b7828df5120a82cc9394a2e94b5befa036e5305898e654212eada980f99ef49c8f7326f68b1d92e7fedc36fb4957f21a40a37bc306f2bcb811ac0a4719

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
